services:
  database:
    image: postgres:16.3
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    networks:
      - taskapp_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_container
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
      - cache
    networks:
      - taskapp_network
    ports:
      - 4000:4000

  cache:
    image: redis:8.0-M03-alpine
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: 6379
      REDIS_DATABASE: ${REDIS_DATABASE}

volumes:
  postgres_data:
  redis_data:

networks:
  taskapp_network:
    driver: bridge