services:
  database:
    image: postgres:16.3
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    networks:
      - taskapp_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_container
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - taskapp_network
    ports:
      - 4000:4000

volumes:
  postgres_data:

networks:
  taskapp_network:
    driver: bridge